### ISSUE TITLE
set the php_ini path in order to the pecl extension

### ISSUE THREAD

**Issue by icai** [hitalos/php#2]
I try to install protobuf extension, but catch the error:

configuration option "php_ini" is not set to php.ini location
You should add "extension=protobuf.so" to php.ini

```sh
pecl config-set php_ini "${PHP_INI_DIR}/php.ini"
```

**Comment by hitalos** [comment]
Try to run:
```
echo "extension=protobuf.so" > /usr/local/etc/php/conf.d/protobuf.ini
```
